name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run server pytest
        run: |
          pytest ./server/tests --cov-config=.coveragerc --cov=server --cov-fail-under=100

      - name: Run auth pytest
        run: |
          pytest ./auth/tests --cov-config=.coveragerc --cov=auth --cov-fail-under=100

      - name: Run player pytest
        run: |
          pytest ./player/tests --cov-config=.coveragerc --cov=player --cov-fail-under=100

      - name: Run server pylint
        run: |
          pylint ./server

      - name: Run auth pylint
        run: |
          pylint ./auth

      - name: Run player pylint
        run: |
          pylint ./player
